### ISSUE TITLE
Improve scoring algorithm

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#5]
Below, copied some old notes I had from https://github.com/okfn/data-quality-dashboard/issues/2

Subsequent work on this codebase never addressed this issue, and it would be good to address this properly (spec here, or user story).

In the results aggregator (https://github.com/okfn/spd-admin/blob/master/spd_admin/tasks.py#L97)

The "algorithm" is simply: start at score of 10, minus 1 per error, down to 0.

Obviously we'll want something a bit smarter: something that perhaps treats structural errors differently to schema errors, or, handles cases for example where one single mistake is repeated over multiple rows.

Ideas?

Factor to consider, based on feedback from team at data.gov.uk ( @davidread ):

"the HMT guidance requires publication one month in arrears, so DfE should not be coloured green for having data up to August, since September should have been published by the end of October."

**Comment by davidread** [comment]
I'm not clear of the advantages of scoring tbh. Pass/fail is simpler to understand and much more defensible - either it gets everything right or it doesn't. Giving a score percentage just seems like an opinion of OKF, opaquely arrived at.

Whether the release was timely or not is a different dimension to whether it validates. Since it is nearly always broken, maybe there is a case saying you should measure the average 'lag' (time after the end of the month) or 'lateness' (time after it should have been published).

**Comment by pwalsh** [comment]
@davidread I'd say part of the goal of the tool is to promote further action. the scoring went down really well when I showed to a range of stakeholders in uk govt. 

Example: if a department consistently gets 90%, and we find out that it is just because of a single column name being done incorrectly, the incentive to get to 100% is much greater, based on knowledge that the fix is _easy_. Contrast this with files that are completely full of errors in schema and structure.

So, I don't think it is an OKF opinion, it is an incentive tool to push to quality. However, maybe it can be done without numbers per se, but indicators like Bad, Better, Perfect - something along those lines.

WDYT?

**Comment by davidread** [comment]
Well if it went down well with users, then great.

My experience of the issues with spend data, and in fact most schema problems, is that the fixes are all pretty quick, compared to the process they go through to prepare the spreadsheet in the first place (extract from accounts, identify rows to redact, get approval). They uploaded the wrong file instead of a spreadsheet. Rename the column headings. Change the date format. Take out an additional column. Remove a spurious blank row. Remove 'N/A' string from the Amount column. Add in the mandatory description on rows where it's missing. So if there's a file uploaded at all they are probably 'nearly' there. So yes, some more encouraging wording than 'pass/fail' would be good. A traffic light with 'amber' meaning uploaded but 'not quite passing yet'?

**Comment by pwalsh** [comment]
@davidread ok. maybe just 3-4 states from red - green will do the trick and be less arbitrary than something like 90%. Great idea, thanks.

**Comment by pwalsh** [comment]
Moving this back onto backlog: we want some user feedback on latest version (in gov.uk and outside, with the new ckan integration) before we make changes to scoring.

**Comment by pwalsh** [comment]
@jobarratt pinging you on here for your thoughts when we get to it.

**Comment by pwalsh** [comment]
Note that this issue related to the scoring in the CLI, and also how we present scores in the app.

**Comment by georgiana-b** [comment]
Latest updates on this:
We agreed on implementing 2 scoring algorithms, one more focused on quantitative  and the other on qualitative analysis. I should provide an example database with each of these.
1. Score based on number of rows affected by each error:
      Algorithm:   `total score  - percent_of_affected_rows`
      Ex:   
   
   ```
             - For a file with 60 rows:
                 - a mistake that appears 3 times :   100 - 1.7 = 98.3
                 - a mistake that appears 10 times:   100 - 6 = 94
                 - a mistake that appears 25 times :  100 - 15 = 85
   ```
2. Score based on the number of occurrences of each error and its weight: 
           -   implies the score will be affected differently by 1 error that occurs 10 times vs 10 distinct errors
           -   allows errors to be weighted differently
       Algorithm:  `total score  -  (no_of_occurrences * error_weight) / (Σ 1/no_of_occurrences )`
                              i.e.`total score - weight * harmonic mean of number of occurrences`
       Ex: 
   
   ```
           - A mistake with weight 1:
               - that appears 3 times:    100 - 1.66 = 98.3
               - that appears 10 times:   100 - 3.44 = 96.5
               - that appears 25 times:   100 - 6.57 = 93.42
   
           - A mistake with weight 2 
               - that appears 3 times:    100 - 3.3 = 96.6
               - that appears 10 times:   100 - 6.8 = 93.1
   
           - 2 mistakes with weight 1
               - that appear 5 times:     100 - 4.38 = 95.6
   ```
3. For a mash up between the above, we could combine the weight with the percent of rows affected: 
   Algorithm:
   `total score - ( error_weight  * percent_of_affected_rows)`
   Ex: 
   
   ```
             -  A mistake with weight 2 in a file with 60 rows:
                   - that appears 3 times:    100 - (2 * 1.7 ) = 96.6
                   - that appears 10 times:   100 - (2 * 6 ) =  88
                   - that appears 25 times:   100 - (2 * 15) = 70
   ```

**Comment by pwalsh** [comment]
Thanks @georgiana-b !
